### ISSUE TITLE
Usage with Babylon.js

### ISSUE THREAD

**Issue by tim-montague** [pmndrs/cannon-es#68] opened 2021-01-17 03:17 UTC
I use Cannon with Babylon.js
[https://doc.babylonjs.com/divingDeeper/physics/usingPhysicsEngine](https://doc.babylonjs.com/divingDeeper/physics/usingPhysicsEngine)

I see many examples with Three.js, but not with Babylon.js, or other frameworks
Is this package for Three.js only?

**Comment by marcofugaro** [comment] 2021-01-17 15:42
> Is this package for Three.js only?

No, it can be used with any rendering engine.
For babylon in particular, [it reads by default the global CANNON variable](https://github.com/BabylonJS/Babylon.js/blob/b766ec0ae16a583228c2029df43f9289730a5906/src/Physics/Plugins/cannonJSPlugin.ts#L29), so it should work the same if you import cannon-es instead of cannon.js:

```js
import * as CANNON from 'cannon-es'

// ...

const physicsPlugin = new BABYLON.CannonJSPlugin()
```

> I see many examples with Three.js, but not with Babylon.js, or other frameworks

There are no non-three.js examples because I am not familiar with other webgl frameworks. But you can make a PR with a basic babylon.js implementation if you want.

**Comment by tim-montague** [comment] 2021-01-18 22:34
Unfortunately, the Cannon-es package causes the CannonJSPlugin to error.
https://forum.babylonjs.com/t/how-does-react-use-the-cannon-js-physics-engine/10275/9
```
TypeError: this.world.add is not a function. (In 'this.world.add(impostor.physicsBody)', 'this.world.add' is undefined)

135 | this.world.addEventListener("preStep", impostor.beforeStep);
136 | this.world.addEventListener("postStep", impostor.afterStep);
137 | impostor.physicsBody.addShape(shape);
> 138 | this.world.add(impostor.physicsBody);
^  139 |
140 | //try to keep the body moving in the right direction by taking old properties.
141 | //Should be tested!
```

Maybe the Babylon.js and Cannon-es team can ensure this works?
https://forum.babylonjs.com/t/how-does-react-use-the-cannon-js-physics-engine/10275/11

**Comment by marcofugaro** [comment] 2021-01-18 23:05
@tim-montague `this.world.add()` has been deprecated and removed. Please use `this.world.addBody()`.

**Comment by tim-montague** [comment] 2021-01-19 05:29
Okay, the README has quite a few improvements listed.
After fixing to `this.world.addBody()`, I get another error with `shape.calculateWorldAABB()`

```javascript
  3590 | 
  3591 | bodyQuat.mult(shapeOrientations[i], orientation); // Get shape AABB
  3592 | 
> 3593 | shape.calculateWorldAABB(offset, orientation, shapeAABB.lowerBound, shapeAABB.upperBound);
^ 3594 | 
  3595 | if (i === 0) {
  3596 |   aabb.copy(shapeAABB);
```

**Comment by marcofugaro** [comment] 2021-01-19 12:03
@tim-montague could you share a reproducible example? It will help with debugging.

Upload it on [codepen](https://codepen.io/) or [codesandbox](https://codesandbox.io/)

**Comment by marcofugaro** [comment] 2021-03-06 13:51
Closing, here is an example of using Babylon.js + cannon-es.

Right now there is the error `this.world.add is not a function` in the console, but it will be fixed when https://github.com/BabylonJS/Babylon.js/issues/9810 will be closed.


```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>cannon.js + babylon.js - basic integration example</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      canvas {
        width: 100vw;
        height: 100vh;
      }
    </style>
  </head>
  <body>
    <canvas id="renderCanvas"></canvas>
    <script src="https://unpkg.com/babylonjs@5.0.0-alpha.12/babylon.js"></script>
    <script type="module">
      import * as CANNON from 'https://unpkg.com/cannon-es@0.17.0/dist/cannon-es.js'

      // Canvas
      const canvas = document.querySelector('#renderCanvas')

      // Engine
      const engine = new BABYLON.Engine(canvas, true)
      window.addEventListener('resize', () => engine.resize())

      // Scene
      const scene = new BABYLON.Scene(engine)

      // Camera
      const camera = new BABYLON.ArcRotateCamera(
        'camera',
        -Math.PI / 2,
        Math.PI / 2.5,
        3,
        new BABYLON.Vector3(0, 0, 0),
        scene
      )
      camera.attachControl(canvas, true)

      // Light
      const light = new BABYLON.HemisphericLight('light', new BABYLON.Vector3(0, 1, 0), scene)

      // Box
      const box = BABYLON.MeshBuilder.CreateBox('box', {}, scene)

      // Physics
      window.CANNON = CANNON // force the usage of cannon-es
      const gravity = new BABYLON.Vector3(0, 0, 0)
      scene.enablePhysics(gravity)

      // Box body
      box.physicsImpostor = new BABYLON.PhysicsImpostor(box, BABYLON.PhysicsImpostor.BoxImpostor, { mass: 1 }, scene)
      box.physicsImpostor.setAngularVelocity(new BABYLON.Quaternion(0, 10, 0, 0))
      box.physicsImpostor._physicsBody.angularDamping = 0.5

      engine.runRenderLoop(() => {
        scene.render()
      })
    </script>
  </body>
</html>
```

**Closed by marcofugaro** 2021-03-06 13:51 UTC

**Comment by frankieali** [comment] 2021-04-01 18:22
I just submitted a PR for BabylonJS/Babylon.js#9810 and it was approved.

**Comment by frankieali** [comment] 2021-04-05 18:47
Support is now available in Babylon.js version 5.0.0-alpha.16
